<?php
namespace App\Application\Http\Resources;
use Illuminate\Http\Request;
use Illuminate\Http\Resources\Json\JsonResource;

class JobApplicationResource extends JsonResource
{
    public function toArray(Request $request): array
    {
        return parent::toArray($request); // TODO: Change the autogenerated stub
    }
}
